---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: rony-eks
  region: ap-southeast-1

managedNodeGroups:
  - name: ng-rony-eks
    instanceType: t3.small
    minSize: 2
    maxSize: 5
    iam:
      withAddonPolicies:
        autoScaler: true

cloudWatch:
  clusterLogging:
    enableTypes: [all]
